version: '3.7'

services:
  db:
    image: postgres:9.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 35432:5432
    restart: unless-stopped
    networks:
      - dbnetwork
 
  adminer:
    container_name: adminer
    image: adminer:4.7.0
    restart: unless-stopped
    expose:
      - "8088"
    networks:
      - dbnetwork

  nginx: 
    image: nginx:latest
    container_name: nginx_adminer
    depends_on:
      - db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:8088
    networks:
      - dbnetwork

networks:
  dbnetwork:

volumes:
  postgres:
