version: '3.7'

services:
  db:
    image: postgres:9.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 35432:5432
    restart: unless-stopped
 
  adminer:
    image: adminer:4.7.0
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  postgres:
